# Generated by Django 4.1.7 on 2023-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bands',
            name='img',
            field=models.ImageField(null=True, upload_to='bands'),
        ),
    ]
