# Generated by Django 4.1.7 on 2023-04-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bands', '0002_bands_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bands',
            options={'ordering': ['name']},
        ),
    ]
