# Generated by Django 4.1.7 on 2023-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
