# Generated by Django 4.1.7 on 2023-05-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_img'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
