# Generated by Django 4.1.7 on 2023-05-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
